spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/trello_clone
    user: postgres
    password: mypgdbpass
    schemas: public
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://postgres:5432/trello_clone
    username: postgres
    password: mypgdbpass
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/trello_clone
    username: postgres
    password: mypgdbpass
    pool:
      initial-size: 2
      enabled: true
      max-size: 10
